package api

import "net/http"

// CrackerUpdate represents the response from the cracker update check endpoint.
// This type is manually defined because the cracker update endpoint is not in the
// OpenAPI specification and therefore not generated by oapi-codegen.
type CrackerUpdate struct {
	LatestVersion string  `json:"latest_version"`
	DownloadURL   *string `json:"download_url"`
	Available     bool    `json:"available"`
	ExecName      *string `json:"exec_name"`
}

// GetLatestVersion returns the latest version of the cracker.
func (c *CrackerUpdate) GetLatestVersion() string {
	return c.LatestVersion
}

// GetDownloadURL returns the download URL pointer.
func (c *CrackerUpdate) GetDownloadURL() *string {
	return c.DownloadURL
}

// GetAvailable returns whether a new cracker version is available.
func (c *CrackerUpdate) GetAvailable() bool {
	return c.Available
}

// GetExecName returns the executable name pointer.
func (c *CrackerUpdate) GetExecName() *string {
	return c.ExecName
}

// CheckForCrackerUpdateResponse is the response from the cracker update check endpoint.
// This type is manually defined because the endpoint is not in the OpenAPI specification.
type CheckForCrackerUpdateResponse struct {
	StatusCode    int
	HTTPResponse  *http.Response
	CrackerUpdate *CrackerUpdate
}

// Status returns the HTTP status line, or an empty string if HTTPResponse is nil.
func (r *CheckForCrackerUpdateResponse) Status() string {
	if r != nil && r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// GetCrackerUpdate returns the CrackerUpdate from the response, or nil if no update data is present.
// Returns nil if the receiver itself is nil, consistent with the nil guard in Status().
func (r *CheckForCrackerUpdateResponse) GetCrackerUpdate() *CrackerUpdate {
	if r == nil {
		return nil
	}
	return r.CrackerUpdate
}
