# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
tone_instructions: "Review as a senior engineer: decisive, direct, focused on production Go code. Flag critical issues immediately. Emphasize error handling, concurrency, and conventions. Use 'must/shall/critical' language."
early_access: true
enable_free_tier: true
inheritance: false
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_instructions: "Focus on technical impact: Go concurrency patterns, API reliability, hashcat integration, security implications, and architectural changes. Prioritize breaking changes, performance impacts, and testing coverage. Structure as: [Core Changes] → [Architecture Impact] → [Risks/Testing] → [Migration Notes]."
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: true
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: "Use Conventional Commits format: type(scope): description. Types: feat, fix, refactor, perf, test, docs, ci. Scopes: cli, api, hashcat, agent, config, arch. Focus on technical changes: concurrency patterns, API reliability, security hardening, hashcat integration."
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  labeling_instructions:
    - label: "go"
      instructions: "Apply for Go code changes (*.go files)"
    - label: "hashcat"
      instructions: "Apply for hashcat-related changes (session.go, params.go, hashcat/ directory)"
    - label: "api"
      instructions: "Apply for API client/server communication changes"
    - label: "security"
      instructions: "Apply for authentication, encryption, or security-related changes"
    - label: "performance"
      instructions: "Apply for performance optimizations or benchmarking changes"
    - label: "testing"
      instructions: "Apply for test file changes or test coverage improvements"
    - label: "docker"
      instructions: "Apply for Dockerfile or containerization changes"
    - label: "refactoring"
      instructions: "Apply for code restructuring without functional changes"
    - label: "technical-debt"
      instructions: "Apply for debt reduction or code quality improvements"
  auto_apply_labels: true
  suggested_reviewers: true
  auto_assign_reviewers: true
  in_progress_fortune: true
  poem: true
  enable_prompt_for_ai_agents: true
  path_filters: ["swagger.json"]
  path_instructions:
    - path: "lib/hashcat/*.go"
      instructions: "Review hashcat integration carefully: session management, parameter validation, output parsing. Ensure proper error handling and resource cleanup."
    - path: "lib/arch/*.go"
      instructions: "Review OS-specific code: ensure platform compatibility, proper abstraction, and no hardcoded paths. Check for cross-platform compatibility."
    - path: "lib/agent/*.go"
      instructions: "Review agent lifecycle: registration, heartbeats, task processing. Verify API contract compliance and error recovery patterns."
    - path: "lib/config/*.go"
      instructions: "Review configuration handling: environment variables, CLI flags, validation. Ensure secrets are never logged and config is immutable."
    - path: "cmd/*.go"
      instructions: "Review CLI entry points: Cobra command structure, flag validation, graceful shutdown. Ensure proper error propagation."
    - path: "*.go"
      instructions: "Standard Go review: error handling with fmt.Errorf/%w, defer for cleanup, context usage, goroutine safety, table-driven tests."
    - path: "docs/*.md"
      instructions: "Review documentation: technical accuracy, adherence to project conventions, completeness for new features."
    - path: "swagger.json"
      instructions: "Review API changes: backward compatibility, proper OpenAPI spec compliance, security implications."
  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "work in progress"
      - "draft"
      - "DO NOT MERGE"
      - "[skip review]"
    labels:
      - "dependencies"
      - "github_actions"
      - "documentation"
    drafts: false
    base_branches:
      - "main"
    ignore_usernames:
      - "dependabot"
      - "renovate"
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  pre_merge_checks:
    docstrings:
      mode: warning
      threshold: 80
    title:
      mode: error
      requirements: "Must follow Conventional Commits format: type(scope): description. Valid types: feat, fix, refactor, perf, test, docs, ci, build, chore. Scopes: cli, api, hashcat, agent, config, arch."
    description:
      mode: warning
    issue_assessment:
      mode: warning
    custom_checks:
      - name: "Go Code Quality"
        mode: error
        instructions: "Ensure Go code is properly formatted with gofmt and passes golangci-lint checks. Run 'just ci-check' to validate."
  tools:
    ast-grep:
      rule_dirs: []
      util_dirs: []
      essential_rules: true
      packages: []
    shellcheck:
      enabled: true
    ruff:
      enabled: false
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: false
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
      enabled_only: false
      level: default
    biome:
      enabled: false
    hadolint:
      enabled: true
    swiftlint:
      enabled: false
    phpstan:
      enabled: false
      level: default
    phpmd:
      enabled: false
    phpcs:
      enabled: false
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: false
    eslint:
      enabled: false
    flake8:
      enabled: false
    fortitudeLint:
      enabled: false
    rubocop:
      enabled: false
    buf:
      enabled: false
    regal:
      enabled: false
    actionlint:
      enabled: true
    pmd:
      enabled: false
    clang:
      enabled: false
    cppcheck:
      enabled: false
    semgrep:
      enabled: false
    circleci:
      enabled: false
    clippy:
      enabled: false
    sqlfluff:
      enabled: false
    prismaLint:
      enabled: false
    pylint:
      enabled: false
    oxc:
      enabled: false
    shopifyThemeCheck:
      enabled: false
    luacheck:
      enabled: false
    brakeman:
      enabled: false
    dotenvLint:
      enabled: true
    htmlhint:
      enabled: false
    checkmake:
      enabled: false
    osvScanner:
      enabled: true
chat:
  art: true
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: [".kiro/**/*.md"]
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto
  mcp:
    usage: auto
    disabled_servers: []
code_generation:
  docstrings:
    language: en-US
    path_instructions:
      - path: "lib/agent/*.go"
        instructions: "Generate comprehensive docstrings for exported functions: describe agent lifecycle, API interactions, error conditions."
      - path: "lib/hashcat/*.go"
        instructions: "Document hashcat operations: session lifecycle, parameter validation, output parsing, resource management."
      - path: "lib/arch/*.go"
        instructions: "Document OS abstractions: platform-specific behavior, compatibility requirements, fallback mechanisms."
      - path: "lib/config/*.go"
        instructions: "Document configuration structs and functions: environment variables, validation rules, default values."
      - path: "cmd/*.go"
        instructions: "Document CLI commands: usage, flags, examples, error conditions."
      - path: "*.go"
        instructions: "Generate docstrings for exported functions/types: purpose, parameters, return values, error conditions."
  unit_tests:
    path_instructions:
      - path: "lib/agent/*.go"
        instructions: "Generate table-driven tests for agent functions: mock API responses, test error conditions, verify state transitions."
      - path: "lib/hashcat/*.go"
        instructions: "Test hashcat operations: parameter validation, session management, output parsing, cleanup on errors."
      - path: "lib/downloader/*.go"
        instructions: "Test download functionality: network errors, file validation, progress tracking, cleanup."
      - path: "lib/config/*.go"
        instructions: "Test configuration parsing: environment variables, CLI flags, validation, defaults, error cases."
      - path: "lib/taskManager/*.go"
        instructions: "Test task lifecycle: state management, concurrency, error recovery, resource cleanup."
      - path: "lib/benchManager/*.go"
        instructions: "Test benchmarking: performance metrics, hardware detection, parameter optimization."
      - path: "cmd/*.go"
        instructions: "Test CLI commands: flag parsing, error handling, help output, integration with core logic."
      - path: "*.go"
        instructions: "Generate unit tests with mocks for external dependencies, table-driven test cases, race detection enabled."
issue_enrichment:
  auto_enrich:
    enabled: true
  planning:
    enabled: true
    auto_planning:
      enabled: false
      labels: []
  labeling:
    labeling_instructions:
      - label: "bug"
        instructions: "Apply for issues reporting software defects or unexpected behavior"
      - label: "enhancement"
        instructions: "Apply for feature requests and improvement suggestions"
      - label: "documentation"
        instructions: "Apply for docs improvements or additions"
      - label: "question"
        instructions: "Apply for clarification requests or support questions"
      - label: "security"
        instructions: "Apply for security vulnerabilities or hardening requests"
      - label: "performance"
        instructions: "Apply for performance issues or optimization requests"
      - label: "hashcat"
        instructions: "Apply for hashcat-specific issues"
      - label: "api"
        instructions: "Apply for API communication or protocol issues"
      - label: "technical-debt"
        instructions: "Apply for code quality or architectural debt issues"
      - label: "good first issue"
        instructions: "Apply for beginner-friendly tasks"
      - label: "help wanted"
        instructions: "Apply for issues needing community contribution"
    auto_apply_labels: true
