style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/unclesp1d3r/CipherSwarmAgent
options:
  commits:
    sort_by: Type
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - docs
        - style
        - test
        - chore
        - Bump
        - Merge
        - Added
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      docs: Documentation
      style: Style Changes
      test: Test Changes
      chore: Chores
      Bump: Dependency Bumps
      Merge: Merge Commits
      Added: Added Features
  issues:
    prefix:
      -  #
  refs:
    actions:
      - Closes
      - Fixes
  header:
    pattern: "^((\\w+)\\s.*)$"
    pattern_maps:
      - Subject
      - Type
  notes:
    keywords:
      - BREAKING CHANGE
